### ISSUE TITLE
Misplaced `nativeImage` flags

### ISSUE THREAD

**Issue by phreed** [formkiq/graalvm-native-plugin#11]
In [sample/helloword](../blob/b7a9ba56007dd14dc370547bfc19f1a3d35c195f/samples/helloworld/app/build.gradle#L32) the enable switches are (incorrectly) placed in the `application` configuration. 

```groovy
// creates binary file 'app/build/graalvm/app'
nativeImage {
    mainClassName = 'helloworld.App'
    enableCheckToolchain = true
    enableReportExceptionStackTraces = true
}
```

**Comment by phreed** [comment]
After making this correction.
When I run this on my Windows 10 environment I get the following error.
```
 ./gradlew graalvmNativeImage

> Task :app:graalvmNativeImage
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
[#                   ]ECUTING [1m 25s]      [##                  ]                      [###     Installing new component: Native Image (org.graalvm.native-image, version 21.0.0)
Warning: Ignoring server-mode native-image argument --no-server.
[app:13084]    classlist:   3,043.27 ms,  0.96 GB
[app:13084]        setup:   1,946.53 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
com.oracle.svm.core.util.UserError$UserException: Default native-compiler executable 'cl.exe' not found via environment variable PATH
To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
        at com.oracle.svm.core.util.UserError.abort(UserError.java:139)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.addSkipCheckingInfo(CCompilerInvoker.java:104)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:72)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$WindowsCCompilerInvoker.<init>(CCompilerInvoker.java:110)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:84)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:877)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

BUILD SUCCESSFUL in 1m 52s
8 actionable tasks: 8 executed
```
How is the `cl.exe` expected to be located? 
I have looked at https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line but I do not see how to get that to work with gradle.

**Comment by mfriesen** [comment]
@phreed I'm not following your comment on "enable switches are (inappropriately) placed". What are you thinking is more appropriate?

I have not tested on Windows only MacOS/Linux as I do not have access to a Windows machine. The plugin simply calls the graalvm compiler so maybe if you follow the graalvm docs it will work? https://www.graalvm.org/docs/getting-started/windows/

**Comment by phreed** [comment]
Here is what is in the 
```groovy
 application {
            // Define the main class for the application.
            mainClass = 'helloworld.App'
            enableCheckToolchain = true
            enableReportExceptionStackTraces = true
  }
  // creates binary file 'app/build/graalvm/app'
  nativeImage {
            mainClassName = 'helloworld.App'
  }
```
`application` does not have an `enableCheckToolchain` or an `enableReportExceptionStackTraces` property `nativeImage` does.
So, it should be.
```groovy
 application {
            // Define the main class for the application.
            mainClass = 'helloworld.App'
  }
  // creates binary file 'app/build/graalvm/app'
  nativeImage {
            mainClassName = 'helloworld.App'
  }
```

**Comment by phreed** [comment]
I will open the Windows issue separately.

**Comment by mfriesen** [comment]
Thanks @phreed for catching the typo. I've updated the build.gradle in the sample app.
