### ISSUE TITLE
GraalVM not finding cl.exe compiler on Windows 10

### ISSUE THREAD

**Issue by phreed** [formkiq/graalvm-native-plugin#12]
After making this correction.
When I run this on my Windows 10 environment I get the following error.
```
 ./gradlew graalvmNativeImage

> Task :app:graalvmNativeImage
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
[#                   ]ECUTING [1m 25s]      [##                  ]                      [###     Installing new component: Native Image (org.graalvm.native-image, version 21.0.0)
Warning: Ignoring server-mode native-image argument --no-server.
[app:13084]    classlist:   3,043.27 ms,  0.96 GB
[app:13084]        setup:   1,946.53 ms,  0.96 GB
Error: Default native-compiler executable 'cl.exe' not found via environment variable PATH
Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
com.oracle.svm.core.util.UserError$UserException: Default native-compiler executable 'cl.exe' not found via environment variable PATH
To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
        at com.oracle.svm.core.util.UserError.abort(UserError.java:139)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.addSkipCheckingInfo(CCompilerInvoker.java:104)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:72)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$WindowsCCompilerInvoker.<init>(CCompilerInvoker.java:110)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:84)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:877)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

BUILD SUCCESSFUL in 1m 52s
8 actionable tasks: 8 executed
```
How is the `cl.exe` expected to be located? 
I have looked at https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line but I do not see how to get that to work with gradle.

**Comment by phreed** [comment]
Where in the plugin is the graalvm compiler invoked.
https://www.graalvm.org/docs/getting-started/windows/
I think the issue is that the environment needs to be conditioned first.
https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line
This may be related to properly setting up the gradle toolchain.

**Comment by phreed** [comment]
I got it working.
The gradle build needs to be run from within the proper environment. 
e.g.
```
```

**Comment by mfriesen** [comment]
@phreed If you could give me the exact steps you did I can add them to the documentation. Thanks.

**Comment by phreed** [comment]
Here are some instructions (partially) plagiarized from https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line 
-----------------------------------
## To open a GraalVM suitable developer command prompt window

On the desktop, open the Windows Start menu, and then scroll to find and open the folder for your version of Visual Studio, for example, Visual Studio 2019.

In the folder, choose the "x64 Native Tools Command Prompt" for your version of Visual Studio.  
This shortcut starts a developer command prompt window that uses the default build architecture of 64-bit, x86-native tools to build 64-bit, x86-native code. 
There are other build architectures available, these do not work with GraalVM.

An even faster way to open the appropriate developer command prompt,
enter "x64 Native Tools Command Prompt" in the desktop search box. 

These command prompt shortcuts are installed in a version-specific Visual Studio folder in your Start menu. 
The Start menu folder and shortcut names may vary depending on the installed version of Visual Studio. 
If you set one, they also depend on the installation Nickname. 
For example, suppose you installed Visual Studio 2019, and you gave it a nickname of Latest. 
The developer command prompt shortcut is named "x64 Native Tools Command Prompt for VS 2019 (Latest)", in a folder named Visual Studio 2019.

**Comment by mfriesen** [comment]
Updated with PR - https://github.com/formkiq/graalvm-native-plugin/pull/13
